#!/usr/bin/env bash
# aggregate-metrics.sh — Metric Aggregator for the @YackShavingSkill framework.
#
# Walk .artifacts/*/adherence_report.md under the git repo root, extract
# each report's task_id / complexity_tier / timestamp (via
# parse-frontmatter.py) and metrics / violations (via parse-report-body.py),
# and emit METRICS.md at the repo root. Four Markdown tables per
# plan_phase_3.org §Issue 13 Phase A step 2:
#   - Per-task (task_id, tier, Reflex Rate, Scope Adherence)
#   - Rollup (total tasks, PASS rate, mean Scope Adherence)
#   - Violations by type (Complexity Creep / Scope Bleed / Style Drift)
#   - Trend (Scope Adherence over time, only emitted when >= 3 reports)
#
# See tools/review/README.md for invocation, exit codes, and examples.
# Reference: plan_phase_3.org §Issue 13, Decision D3.

set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
lib="$script_dir/lib"

usage() {
  cat <<'EOF'
Usage: aggregate-metrics.sh

Walks .artifacts/*/adherence_report.md under the git repo root and
writes METRICS.md at the repo root. Four Markdown tables: Per-task,
Rollup, Violations by type, Trend (Trend only when >= 3 reports).

Exit codes:
  0  METRICS.md written successfully.
  1  No adherence reports found under .artifacts/.
  2  Unable to parse one or more reports, or invalid arguments.
EOF
}

die() { echo "error: $*" >&2; exit 2; }

case "${1:-}" in
  -h|--help) usage; exit 0 ;;
  '') ;;
  *) die "unknown argument: $1" ;;
esac

repo_root=$(git rev-parse --show-toplevel) || die "not inside a git repo"

reports=()
while IFS= read -r -d '' f; do
  reports+=("$f")
done < <(find "$repo_root/.artifacts" -mindepth 2 -maxdepth 2 \
  -name adherence_report.md -print0 2>/dev/null | sort -z)

if [ ${#reports[@]} -eq 0 ]; then
  echo "error: no adherence reports found at" \
    "$repo_root/.artifacts/*/adherence_report.md" >&2
  exit 1
fi

# --- Per-report extraction ---
per_task_rows=()
trend_rows=()
total=0
pass_count=0
sa_sum=0
cc_total=0
sb_total=0
sd_total=0

for f in "${reports[@]}"; do
  task_id=$(python3 "$lib/parse-frontmatter.py" read-field "$f" task_id) \
    || die "parse-frontmatter read-field task_id failed on $f"
  tier=$(python3 "$lib/parse-frontmatter.py" read-field "$f" complexity_tier) \
    || die "parse-frontmatter read-field complexity_tier failed on $f"
  ts=$(python3 "$lib/parse-frontmatter.py" read-field "$f" timestamp) \
    || die "parse-frontmatter read-field timestamp failed on $f"

  metrics_line=$(python3 "$lib/parse-report-body.py" metrics "$f") \
    || die "parse-report-body metrics failed on $f"
  violations_line=$(python3 "$lib/parse-report-body.py" violations "$f") \
    || die "parse-report-body violations failed on $f"

  # Issue #28: 2-column metrics (reflex, scope_adherence) instead of 3
  IFS=$'\t' read -r reflex sa <<< "$metrics_line"
  IFS=$'\t' read -r cc sb sd <<< "$violations_line"

  per_task_rows+=("| $task_id | $tier | $reflex | ${sa}% |")
  trend_rows+=("$ts"$'\t'"| $ts | $task_id | ${sa}% |")

  total=$((total + 1))
  [ "$reflex" = "PASS" ] && pass_count=$((pass_count + 1))
  sa_sum=$((sa_sum + sa))
  cc_total=$((cc_total + cc))
  sb_total=$((sb_total + sb))
  sd_total=$((sd_total + sd))
done

# --- Rollup computations (awk for integer division with rounding) ---
pass_rate=$(awk "BEGIN { printf \"%.0f\", $pass_count * 100 / $total }")
sa_mean=$(awk "BEGIN { printf \"%.1f\", $sa_sum / $total }")

# --- Trend sorted by timestamp (column 1); strip the sort key ---
trend_sorted=$(printf '%s\n' "${trend_rows[@]}" | sort | cut -f 2-)

# --- Emit METRICS.md ---
out="$repo_root/METRICS.md"
now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
{
  echo "---"
  echo "artifact_type: metrics_rollup"
  echo "timestamp: $now"
  echo "source_count: $total"
  echo "---"
  echo
  echo "# Metrics — @YackShavingSkill"
  echo
  echo "Aggregated across all \`.artifacts/*/adherence_report.md\` present"
  echo "at snapshot time. Generated by \`tools/review/aggregate-metrics.sh\`;"
  echo "re-run to refresh."
  echo
  echo "Metric semantics are **forward-looking**: the cumulative counts below"
  echo "include historical **tombstones** — violations that were recorded in an"
  echo "adherence report and later corrected in-code. Tombstones persist in"
  echo "this rollup because adherence reports are frozen at commit time, but"
  echo "they do not represent current drift. Canonical definition:"
  echo "\`UBIQUITOUS_LANGUAGE.md\` §5.2 Tombstone."
  echo
  echo "## Per-task"
  echo "| task_id | tier | Reflex Rate | Scope Adherence |"
  echo "|---------|------|-------------|-----------------|"
  printf '%s\n' "${per_task_rows[@]}"
  echo
  echo "## Rollup"
  echo "| Metric | Value |"
  echo "|--------|-------|"
  echo "| Total tasks | $total |"
  echo "| PASS rate (Reflex) | ${pass_rate}% |"
  echo "| Mean Scope Adherence | ${sa_mean}% |"
  echo
  echo "## Violations by type"
  echo "| Type | Count across all tasks |"
  echo "|------|------------------------|"
  echo "| Complexity Creep | $cc_total |"
  echo "| Scope Bleed | $sb_total |"
  echo "| Style Drift | $sd_total |"
  if [ "$total" -ge 3 ]; then
    echo
    echo "## Trend"
    echo "| timestamp | task_id | Scope Adherence |"
    echo "|-----------|---------|-----------------|"
    printf '%s\n' "$trend_sorted"
  fi
} > "$out"

echo "wrote $out ($total report(s) aggregated)" >&2
exit 0
